-- ═══════════════════════════════════════════════════════════════════════════
-- StreamVault – Phase 4 Database Setup
-- Run this file in MySQL BEFORE starting the web application.
-- ═══════════════════════════════════════════════════════════════════════════

-- 1. Select the database
USE streamvault;

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 1 – Add Phase 4 security columns to Users (if not already present)
-- ═══════════════════════════════════════════════════════════════════════════

-- Add password_hash (replaces any plain-text password column from Phase 2)
ALTER TABLE Users
    ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255) NOT NULL DEFAULT '' AFTER email;

-- Add role for RBAC
ALTER TABLE Users
    ADD COLUMN IF NOT EXISTS role VARCHAR(30) NOT NULL DEFAULT 'subscriber' AFTER password_hash;

-- Add is_active flag (soft delete)
ALTER TABLE Users
    ADD COLUMN IF NOT EXISTS is_active TINYINT(1) NOT NULL DEFAULT 1 AFTER role;

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 2 – Add is_available flag to ContentItems (for soft-delete / drafts)
-- ═══════════════════════════════════════════════════════════════════════════

ALTER TABLE ContentItems
    ADD COLUMN IF NOT EXISTS is_available TINYINT(1) NOT NULL DEFAULT 1;

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 3 – Verify structure
-- ═══════════════════════════════════════════════════════════════════════════

DESCRIBE Users;
DESCRIBE ContentItems;

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 4 – Insert test users with BCrypt hashes
--
-- IMPORTANT: These hashes are BCrypt(cost=12) for the passwords below.
-- DO NOT use plain text passwords — only password_hash is stored.
--
-- admin@streamvault.com     password: Admin@1234
-- subscriber@streamvault.com password: Sub@1234
-- ═══════════════════════════════════════════════════════════════════════════

-- NOTE: Replace the hash values with ones generated by your Java app on first run,
-- OR use these pre-generated BCrypt hashes (cost=12):

INSERT IGNORE INTO Users (full_name, email, password_hash, country, date_of_birth, role, is_active)
VALUES
  ('Admin User',    'admin@streamvault.com',
   '$2a$12$eXq3hQ2TXv3PL9C3wBbX5O8zI1yJkT4gR5mN7pA2sU9dE6fK0lMvW',
   'UAE', '1990-01-01', 'admin', 1),

  ('Sara Alzaidi',  'sara@streamvault.com',
   '$2a$12$eXq3hQ2TXv3PL9C3wBbX5O8zI1yJkT4gR5mN7pA2sU9dE6fK0lMvW',
   'Iraq', '1998-05-15', 'subscriber', 1),

  ('Heba Daher',    'heba@streamvault.com',
   '$2a$12$eXq3hQ2TXv3PL9C3wBbX5O8zI1yJkT4gR5mN7pA2sU9dE6fK0lMvW',
   'Sweden', '2000-03-22', 'subscriber', 1);

-- ⚠️  The hash above is a PLACEHOLDER.
--     To get a REAL hash, run the RegisterServlet (create account via the website),
--     OR generate with this Java snippet in a main() method:
--
--     System.out.println(BCrypt.hashpw("Admin@1234", BCrypt.gensalt(12)));
--
--     Then UPDATE Users SET password_hash = '<result>' WHERE email = 'admin@streamvault.com';


-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 5 – Sample subscription plans (if SubscriptionPlan table is empty)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT IGNORE INTO SubscriptionPlan (plan_name, price, features)
VALUES
  ('Basic',    9.99,  'HD streaming, 1 screen'),
  ('Standard', 15.99, 'Full HD, 2 screens'),
  ('Premium',  19.99, '4K Ultra HD, 4 screens, Downloads');

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 6 – Link sample users to plans (if Subscriptions table is empty)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT IGNORE INTO Subscriptions (user_id, plan_id, status, start_date)
SELECT u.user_id, sp.plan_id, 'active', CURDATE()
FROM Users u
JOIN SubscriptionPlan sp ON sp.plan_name = 'Standard'
WHERE u.email IN ('sara@streamvault.com', 'heba@streamvault.com')
  AND NOT EXISTS (
    SELECT 1 FROM Subscriptions s WHERE s.user_id = u.user_id
  );

-- ═══════════════════════════════════════════════════════════════════════════
-- STEP 7 – Sample Studios and ContentItems (quick start data)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT IGNORE INTO Studios (studio_id, name, country)
VALUES
  (1, 'Vault Studios',    'USA'),
  (2, 'Desert Films',     'UAE'),
  (3, 'Nordic Vision',    'Sweden');

INSERT IGNORE INTO ContentItems
  (content_id, studio_id, title, content_type, synopsis, release_year,
   duration_minutes, language, age_rating, is_available)
VALUES
  (1, 1, 'Code Hunters',      'Series',       'Elite hackers race to stop a rogue AI.',
   2024, 45,  'English', 'PG-13', 1),
  (2, 2, 'Desert Storm',      'Movie',        'An action thriller set in the UAE desert.',
   2023, 118, 'Arabic',  'PG-13', 1),
  (3, 3, 'Northern Lights',   'Documentary',  'A journey through Scandinavia.',
   2022, 90,  'English', 'G',     1),
  (4, 1, 'Galactic Echoes',   'Movie',        'Humanity's last mission across the galaxy.',
   2024, 135, 'English', 'PG-13', 1),
  (5, 2, 'The Last Oasis',    'Series',       'Survival drama in a post-water future.',
   2025, 50,  'Arabic',  'TV-14', 1);

INSERT IGNORE INTO Genres (genre_id, name) VALUES
  (1, 'Action'), (2, 'Sci-Fi'), (3, 'Documentary'),
  (4, 'Drama'),  (5, 'Thriller'), (6, 'Adventure');

INSERT IGNORE INTO ContentGenre (content_id, genre_id) VALUES
  (1,1),(1,2),(2,1),(2,5),(3,3),(3,6),(4,2),(4,6),(5,4),(5,5);

INSERT IGNORE INTO Episodes (content_id, season_number, episode_number, title, duration_minutes, synopsis)
VALUES
  (1,1,1,'Pilot Hunt',      45,'The team assembles for their first mission.'),
  (1,1,2,'Firewall Break',  42,'A critical server falls under attack.'),
  (1,2,1,'Zero Day',        48,'An unknown vulnerability is discovered.'),
  (5,1,1,'The Dry Season',  50,'Water supplies reach critical levels.'),
  (5,1,2,'Underground',     47,'A hidden oasis is discovered deep below.');

-- ═══════════════════════════════════════════════════════════════════════════
-- DONE. Now start Tomcat in IntelliJ and open:
-- http://localhost:8080/streamvault/
-- ═══════════════════════════════════════════════════════════════════════════
